namespace Gauge.Protocol;

public enum GaugeCommand : byte
{
    Bootload = 10,
    ResetDevice = 11,
    Identify = 12,
    TxEnable = 13,
    TxDisable = 14,
    TxDischargeDisable = 15,
    AdcAn1 = 16,
    AdcAn4 = 17,
    AdcTemp = 18,
    AdcStream = 19,
    SetPulseInterval = 20,
    SetAcousticAddress = 21,
    ReadInternalEeprom = 22,
    WriteInternalEeprom = 23,
    ReadExternalEeprom = 24,
    WriteExternalEeprom = 25,
    TxByte = 26,
    TxPacket = 27,
    ReadAcousticPacket = 28,
    ResetAcousticPacket = 29,
    EraseExternalMemory = 30,
    ReadFileSector = 31,
    ReadRecordSector = 32,
    TestExternalMemory = 33,
    GetMemoryTestResult = 34,
    StartPll = 35,
    StopPll = 36,
    SensorPowerOn = 37,
    SensorPowerOff = 38,
    FindEndOfFile = 39,
    InitialiseSensor = 40,
    ReadSensorSerial = 41,
    ReadSensorCalibration = 42,
    ReadSensorPressurePolynomial = 43,
    ReadSensorTemperaturePolynomial = 44,
    PowerOffSensor = 45,
    SetMeasureRate = 46,
    SetCalibrationMode = 47,
    DumpCoreLog = 48,
    SetSerialPassMode = 49,
    SetMemoryMode = 50,
    EraseErrorLog = 51,
    MemoryStatus = 52,
    EndMemoryErase = 53,
    SetTxInterval = 54,
    SetCommandReceived = 55,
    GetLastPressureTemperature = 56,
    ToggleTriggerSelect = 57,
    GetRecordSettings = 58,
    SetRecordSettings = 59,
    GetDeviceStatus = 60,
    GetTimestamp = 61,
    ToggleSensorInstalled = 62,
    StartSensorMeasurement = 63
}

